### ISSUE TITLE
processing-sublime can't find libraries

### ISSUE THREAD

**Issue by theowgp** [b-g/processing-sublime#103]
Hi Benedikt!

I tried to use SubblimeText 3 with Processing 3 following all the instruction described for Linux. 
But when I build the project I get the following error:

No library found for ddf.minim
Libraries must be installed in a folder named 'libraries' inside the 'sketchbook' folder.
cat.pde:0:0:0:0: The package âddfâ does not exist. You might be missing a library.
[Finished in 5.4s with exit code 1]
[cmd: ['processing-java', '--force', '--sketch=/home/me/Documents/MP/cat', '--output=/home/me/Documents/MP/cat/build-tmp', '--run']]

The path to my sketchbook is "/home/me/sketchbook", I downloaded the library minim automatically using the Processing application. When I run it from the Processing application everything works fine. Furthermore, if I run the "processing-java --force --sketch=/home/me/Documents/MP/cat --run" from the command line it works fine too. 

What might be the problem ? 
Please help.

Thanks!
Viele grüße,
Myroslav

**Comment by theowgp** [comment]
Hi, 

I changed the access to ~/.config/sublime-text-3 folder, and it helped. But I still don't quite understand why that was the problem.

Myroslav

**Comment by b-g** [comment]
Glad that it worked out. I'm not a linux user. Sorry, no idea :)
