### ISSUE TITLE
What's the license for processing-sublime?

### ISSUE THREAD

**Issue by b-g** [b-g/processing-sublime#107]
Hi @ybakos,

A belated happy new 🎉! There was just a question on twitter https://twitter.com/tobiahzarlez/status/687069119967973378 ... I guess this won't hurt, or? :) Any preferences?

cc/ @TobiahZ

**Comment by ybakos** [comment]
Likewise! I hope all is well with the growing family. :baby: :hankey: 

Yeah, we should add a LICENSE and CONTRIBUTING file, which is typical for projects on GitHub. I looked around and it seems like a lot of the Sublime packages use the MIT license. If you're fine with that, let me know and I can add the two files.

**Comment by b-g** [comment]
Thanks! :)

Yes, then let's go for the MIT LICENSE! http://choosealicense.com/licenses/mit/

However I'm not so fond of moving the contributor section of the readme to an "external" CONTRIBUTING file. As we don't have that many, my gut feeling is that we acknowledge them more if we list them directly in the readme. Or what do you think?

**Comment by ybakos** [comment]
I kept **CONTRIBUTING.md** quite simple and of course left the acknowledgements alone on the README.

**Comment by b-g** [comment]
👍! Thanks!
