### ISSUE TITLE
Still working with processing 3.0.2?

### ISSUE THREAD

**Issue by Jones-S** [b-g/processing-sublime#110]
I see that this repo has not been changed for quite a time.
Does it still work with the current version of processing (3.0.2) on Mac OS X El Capitan?

Cheers

**Comment by ybakos** [comment]
Yes.
(Please use the issues feature for bug reports and feature requests.)

**Comment by Jones-S** [comment]
Alright, thanks. Just for the next time. How would you get in contact with a developer if not via issues. Is there a message-tool?
