### ISSUE TITLE
error on build after updating processing to 3.1

### ISSUE THREAD

**Issue by lowenf** [b-g/processing-sublime#111]
hi, thanks for building this! Just been recently (~2 days) using it and today after updating I'm getting the following error: 

err is java.lang.reflect.InvocationTargetExceptionException in thread "main" 
java.lang.NullPointerException
	at processing.mode.java.Commander.<init>(Commander.java:263)
	at processing.mode.java.Commander.main(Commander.java:86)

I tried re-installing 'processing-java' from the tools menu and change the cmd var in 'Processing.sublime-build' (I installed for all users) but alas no solution..

**Comment by ybakos** [comment]
Thanks @lowenf . There's a bug in the latest _processing-java_. I'll post an issue on github.com/processing/processing and hopefully submit a PR that fixes it.

**Comment by ybakos** [comment]
This will be fixed in Processing 3.1.1.
