### ISSUE TITLE
Why I cannot use it normally?

### ISSUE THREAD

**Issue by Juddd** [b-g/processing-sublime#113]
After I click <kbd>Ctrl</kbd>+<kbd>B</kbd>,It will give two errors like following.

![44](https://cloud.githubusercontent.com/assets/10048069/15229076/ef2efa2a-18c1-11e6-8bcb-6917645d8380.png)

But in my other computer.I can use it normally.Can you help me?It confuse me some time.

**Comment by ybakos** [comment]
It's a Processing 3.1 bug. See https://github.com/processing/processing/issues/4455
