### ISSUE TITLE
OSX Error Message: 'I don't know anything about -sketch=/Users/sysuser1/Desktop/Programming/Chatbots/twitbot/processing_example/.'

### ISSUE THREAD

**Issue by DanHaddock** [b-g/processing-sublime#115]
Hi All,

I have taken a look here - https://github.com/ybakos/processing-sublime/commit/ea8d57ddd9e94b731b0a05db439680a407b6d9db
- and tried to launch using the ~/ at the beginning, no luck on that one.

Also, I read [this article](https://github.com/b-g/processing-sublime/issues/81) regarding the NPM solution for fixing mac paths in Processing 3. This could fix it, does anyone know the npm install 'package name'? I will add it in a give that a go.

Look forward to hearing from anyone who may be able to help me out.

Also, happy to answer any questions about the location of my apps and directories as needed.

Kind regards,

Dan

**Comment by ybakos** [comment]
Please describe what you are trying to do.
Have you run `processing-java` successfully from the command line?

**Comment by DanHaddock** [comment]
Haha yes, it was my fault. I didn't realise that you have to have the Processing program closed before running the processing-java command.
