### ISSUE TITLE
Single line comments aren't greyed out outside of a function

### ISSUE THREAD

**Issue by arashout** [b-g/processing-sublime#116]
I'm not quite sure why but single line comments outside of a function don't get greyed out, as in they are not recognized as comments
```
 Card [] testingSet; // THESE COMMENTS ARE NOT GRAYED OUT
 Card [] trainingSet; //  THESE COMMENTS ARE NOT GRAYED OUT

 void loadData() { // In this function we initialise all out data in two seperate arrays, training[] and test[]
 }
```

**Comment by ybakos** [comment]
Hi @arashout , this seems to be a problem with your particular color theme, as it works fine for me. For example, switch to any of the built-in sublime color themes, and you'll see that comments are styled correctly.
