### ISSUE TITLE
Not Working on windows

### ISSUE THREAD

**Issue by Quillbert** [b-g/processing-sublime#121]
I have followed the instructions for windows, but whenever I try to run a sketch I get this error:
'wmic' is not recognized as an internal or external command,
operable program or batch file.
[Finished in 0.1s with exit code 1]
[shell_cmd: wmic process where "Caption Like '%java.exe%' AND CommandLine Like '%sketch%'" call terminate 1>nul && processing-java --force --sketch="C:\Users\andrewhamby22\Desktop\sketch" --output="C:\Users\andrewhamby22\Desktop\sketch/build-tmp" --run]
[dir: C:\Users\andrewhamby22\Desktop\sketch]
[path: C:\Users\andrewhamby22\Desktop\processing-3.3.7\;C:\Users\andrewhamby22\Desktop\processing-3.3.7\]

**Comment by ybakos** [comment]
@Quillbert This isn't a package issue. See https://superuser.com/questions/1178674/wmic-is-not-recognized-as-an-internal-or-external-command-operable-program-or
