### ISSUE TITLE
How to remove build-temp when the sketch stop to run

### ISSUE THREAD

**Issue by knupel** [b-g/processing-sublime#125]
Hello I try to find how to remove automatically the folder `build-temp` when the sketch stop to run, but I find no comment, post or anything about that. 
Configuration :  Processing 4 / Sublime text 4 / Os Monterey

Before that I'm on Processing 3 / OS Mojave and that's work. 

So I'm pretty sure there is a preference or method to do that... but I cannot find it again. So I must add rule to `gitignore` to don't push and that's take a memory on my laptop too. This is not really clean :)

Et voilà mon problème.

**Comment by ybakos** [comment]
Hi @StanLepunK ,
You can customize the build command to save the build artifacts in a directory of your choosing. For example, change the `--output` option. See https://github.com/b-g/processing-sublime/blob/master/Build%20Systems/Processing.sublime-build .

This plugin relies on the behavior of `processing-java`, and we do not control that. But you can customize this plugin's usage of `processing-java` to suit your preference.

**Comment by knupel** [comment]
Marvelous, that's work like a charm.
Thanks a lot
