### ISSUE TITLE
Persistent array index out of bounds error

### ISSUE THREAD

**Issue by hughrawlinson** [b-g/processing-sublime#29]
Hi,

I keep getting the following error whenever I try and run any sketch:

```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 0
    at processing.app.Sketch.getCode(Sketch.java:1374)
    at processing.mode.java.Commander.statusError(Commander.java:319)
    at processing.mode.java.Commander.<init>(Commander.java:291)
    at processing.mode.java.Commander.main(Commander.java:97)
[Finished in 2.5s with exit code 1]
[cmd: ['processing-java', '--sketch=/Users/Hugh/Documents/Software Development/Processing/perception+multimedia+computing/week3lab/1', '--output=/Users/Hugh/Documents/Software Development/Processing/perception+multimedia+computing/week3lab/1/build-tmp', '--run', '--force']]
[dir: /Users/Hugh/Documents/Software Development/Processing/perception+multimedia+computing/week3lab/1]
[path: /usr/bin:/bin:/usr/sbin:/sbin]
```

This happens when I'm not even using arrays with my code. I made sure it wasn't my code by testing with the following sketch:

``` java
void setup(){
  size(200,200);
}
void draw(){
  // do nothing
}
```

The weird thing is though, it works sporadically. When I was using it today in class, it worked fine. When I got home though, it started giving me this error.

Any help would be much appreciated. Thanks!

**Comment by MaxValue** [comment]
Hey fellow issue commenters and other people feeling stumped on this problem! I found the general reason why this happens:

Your filenames have to follow specific rules:

- must not contain dashes `-` (taken from issue processing/processing#4861)
- must not start with a number `0123456789` (taken from issue processing/processing#2152)
- must not start with an underscore `_`  (taken from issue processing/processing#2152)
- must adhere to [Java class naming rules](https://docs.oracle.com/javase/specs/jls/se11/html/jls-3.html#jls-3.8) (this was the most recent official documentation link I could find), [see here](https://stackoverflow.com/a/65490/7574329) for the gist of it.

**Comment by MaxValue** [comment]
I think just copying is good, because I don't know in which style you want it to be written.

Very happy to see that you want this to be documented!

**Comment by b-g** [comment]
@MaxValue done, see https://github.com/b-g/processing-sublime/commit/9584bfec29f748c86ad75ba4db5a051168bce3ec

**Comment by MaxValue** [comment]
Thank you!

Merry christmas to all!
