### ISSUE TITLE
Sublime text 3 won't build 

### ISSUE THREAD

**Issue by udibob** [b-g/processing-sublime#62]
Hi
I'm using sublime text 3, and when trying to build processing I'm getting:
[WinError 2] The system cannot find the file specified
[cmd: ['processing-java', '--sketch=C:\\Users\\Udi Bobrovsky\\Google Drive\\ Out of context\\processing\\build', '--output=C:\\Users\\Udi Bobrovsky\\Google Drive\\ Out of context\\processing\\build/build-tmp', '--run', '--force']]
[dir: C:\Users\Udi Bobrovsky\Google Drive\ Out of context\processing\build]
[path: C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\iis express\PHP\v5.4;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x86;C:\Program Files (x86)\Intel\OpenCL SDK\2.0\bin\x64;C:\Program Files (x86)\Common Files\Ulead Systems\MPEG;C:\SWTOOLS\ReadyApps;C:\Program Files (x86)\Common Files\Lenovo;C:\Program Files\Common Files\Autodesk Shared\;C:\Program Files (x86)\Autodesk\Backburner\;C:\Program Files\MySQL\MySQL Server 5.1\bin;C:\Users\Udi Bobrovsky\AppData\Roaming\MarketView\MarketView ExcelTools\]
[Finished]

Also, I can see no processing-java file is being created under the build folder.

I've got Processing2.2.1 installed
Run Processing Java
Installed Processing package for Sublime text 3

I just can't compile...

**Comment by iamrphy** [comment]
I'm having the same issue. What did you do to fix it?

**Comment by udibob** [comment]
Long time ago...

Restarted the whole process from the beginning, and followed it thoroghly

Udi Bobrovsky
E-mail:  udibob@gmail.com
Mobile: +972 54 4560008
Skype:  bobbob1234

**Comment by b-g** [comment]
Hi @udibob , does the "java-processing" command work in your windows cmd? Or even solved now?
