### ISSUE TITLE
Feature Request: Automatic enclosing folder creation

### ISSUE THREAD

**Issue by ejproj** [b-g/processing-sublime#63]
Does anyone know of an automatic means for creating the required enclosing folder of the same name for .pde sketches? I've seen it mentioned but haven't found a good method or workaround.

Cheers for the good work so far!

**Comment by b-g** [comment]
Thanks! + Sorry don't have a good solution either. Also I don't want to introduce this in the build process ... too much room for errors for very little gain. I hope this ok for you. Best, Benedikt

**Comment by mildlydiverting** [comment]
I know this is closed, but +1 for this. As someone learning processing and coding and sublime text at the same time, this would be really useful - as the build process expects the pde in a folder.
