### ISSUE TITLE
Feature: Close previous sketches upon re-build.

### ISSUE THREAD

**Issue by akaleeroy** [b-g/processing-sublime#64]
I was able to change the build system to not open multiple sketches. Edit `Processing.sublime-build`, which you can find in `Sublime Text\Data\Installed Packages\Processing.sublime-package`, unzip it as an archive. Then place this new version in `Sublime Text\Data\Packages\User` or replace it inside the `.sublime-package`:

    {
      "selector": "source.pde",
      "cmd": ["processing-java", "--sketch=$file_path", "--output=$file_path/build-tmp", "--run", "--force"],
      "file_regex": "^(...*?):([0-9]*)",
      "encoding": "ISO8859-1",

      "windows": {
        // Kills ALL running sketches first then builds
        // "shell_cmd": "tskill java 2>nul & processing-java --sketch=\"$file_path\" --output=%TEMP%\\build-tmp --run --force"
        
        // Kills that sketch if it exists first then builds
        "shell_cmd": "wmic process where \"Caption Like '%java.exe%' AND CommandLine Like '%$file_base_name%'\" call terminate 1>nul && processing-java --sketch=\"$file_path\" --output=%TEMP%/build-tmp --run --force"
      },

      // "variants": [bla bla] snipped

- `"shell": true` or using `shell_cmd`  enables multiple command chaining and Windows Environment Variables like %TEMP%

- `tskill` command kills the Java process, suppressing errors *ERROR java.exe not found*

- `wmic` command tries to find if the sketch you want to build is already running, and kills the old process before starting the new one.  Only available on Windows 7 and up.

- Changing the `--output` path to `%TEMP%` because keeping sketches in Dropbox makes you constantly upload and delete `build-tmp` folders. So I chose user Temp folder `C:\Users\Me\AppData\Local\Temp`

---
*Edited 6 May 2015*: Improved build system code

**Comment by b-g** [comment]
Hi @akaleeroy, this super! However I'm struggle to include this feature in the official build system as you would have to test this for every windows version which ST currently can run on. Hence I think it would be better to include a howto "close old sketch on build" in the readme. Can you provide that via a pull request?

**Comment by akaleeroy** [comment]
I would put it in the readme, but I believe the `wmic` command works on all Windows versions XP and up. If you want I can try to download VMs and test. Or you could choose to include it as a variant instead of the default build system for Windows.
