### ISSUE TITLE
problem using shortcut

### ISSUE THREAD

**Issue by swortain** [b-g/processing-sublime#67]
hi, I have a problem when I built with shortcut in windows.

 1. at first I didn't add the code in the key bindings file.
    I can't build with both ctrl+b or ctrl+shift+b, but it works with command: built with procesing and fullscreen. it saied "no built system with variant Run" when I type ctrl+shift+b
 2. then I added the code, but nothing changed.
 3. when I changed the code like this:
    `{ "keys": ["ctrl+b"], "command": "build", "context":[{ "key": "selector", "operator":"equal", "operand": "source.pde" }]},
    { "keys": ["ctrl+shift+b"], "command": "build", "args": {"variant": "Run sketch fullscreen"}, "context":[{ "key": "selector", "operator": "equal", "operand": "source.pde" }
    ]}`
    Now I can build sketch fullscreen with shortcut ctrl+shift+b, but it still doesn't work with ctrl+b

Thanks!

**Comment by b-g** [comment]
I'm afraid ... this seems rather to be a general ST issue ... Sorry! Plz post there.
