### ISSUE TITLE
Consider moving ownership of repository to the processing foundation org

### ISSUE THREAD

**Issue by ybakos** [b-g/processing-sublime#79]
It might be beneficial to move the ownership of this repo to the official Processing foundation GitHub org. It's up to @b-g, and I understand if he wants to maintain ownership. But I think there are some benefits to moving it, and I think it "feels" right.

For discussion when @b-g is back online after the summer.

/cc @benfry @reas

**Comment by ybakos** [comment]
@b-g What is your feeling about this?

**Comment by benfry** [comment]
I'm not looking to take on responsibility for more projects. It's fine as it is.
