### ISSUE TITLE
Change the path for a new processing

### ISSUE THREAD

**Issue by StanLepunK** [b-g/processing-sublime#80]
I change Processing from 3.0a5 to 3.0b5
I reinstall processing Java from Processing 3.0b5. I uninstall the processing package, to install a new one.
But when I want built my sketch I've this message : Sublim seach the old past : /usr/bin/processing-java: line 2: /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_72.jdk/Contents/Home/jre/bin/java: No such file or directory

but the adress is jdk1.8.0_60.jdk 

Where is it's possible to change this address ? I'm on OSX  

Thx

**Comment by b-g** [comment]
Hi! I don't get it. What do you mean with "address"? Plz clarify :)

**Comment by b-g** [comment]
+ Can you run `processing-java` on the command line and check whether it works?

**Comment by StanLepunK** [comment]
Hi,
I"m not familiar with command line :(
I mean by adress, where sublim must find the good jdk to run processing in sublim : 
/Applications/Processing.app/Contents/PlugIns/jdk1.7.0_72.jdk/Contents/Home/jre/bin/java: No such file or directory 
instead sublim must go to "jdk1.8.0_60.jdk" not "jdk1.7.0_72.jdk" because this one is for Processing 3.0a5 and don't exist anymore to this adress, so sublim cannot find him. I hope is more clear ?

**Comment by StanLepunK** [comment]
I search why Sublim search this adress and change something, but I don't find... i continue my investigation :)

**Comment by StanLepunK** [comment]
Just in case I try to change the name of the folder "jdk1.8.0_60.jdk" to "jdk1.7.0_72.jdk" but sublim return me this message  
Error : not possible to find or load the main class processing.mode.java.Commander it's my translation from french ! "Erreur : impossible de trouver ou charger la classe principale processing.mode.java.Commander"

**Comment by ybakos** [comment]
@StanLepunK Please run `processing-java` from the command line, and let us know what you see.

**Comment by StanLepunK** [comment]
I'm not very good with the terminal but I've tried : when I use Processing 3.0b5 the result is
"Erreur : impossible de trouver ou charger la classe principale processing.mode.java.Commander"
Error : not possible to find or load the main class prossecing.mode.java.commander
When I used Processing 3.0a5
the result is
--help               Show this help text. Congratulations.

--sketch=<name>      Specify the sketch folder (required)
--output=<name>      Specify the output folder (optional and
                     cannot be the same as the sketch folder.)

--force              The sketch will not build if the output
                     folder already exists, because the contents
                     will be replaced. This option erases the
                     folder first. Use with extreme caution!

--build              Preprocess and compile a sketch into .class files.
--run                Preprocess, compile, and run a sketch.
--present            Preprocess, compile, and run a sketch full screen.

--export             Export an application.
--no-java            Do not embed Java. Use at your own risk!

**Comment by StanLepunK** [comment]
it don't fing the maion class when I try to change the name of the folder of "jdk1.8.0_60.jdk" to "dk1.7.0_72.jdk"
but with the original jdk of Processing 3.0b5 the terminal return 
/usr/bin/processing-java: line 2: /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_72.jdk/Contents/Home/jre/bin/java: No such file or directory

**Comment by StanLepunK** [comment]
I clean all the setting of Sublime and re-install a new package, but same answer 
but When I ape in the console direct "java-processing", the computer search for the old jdk, but when I tape /Users/stanislasmarcais/processing-java the computer found the good one. The probleme it's than sublim find the bad one. I don't understand because I remove all the "processing-java" before install a new one from Processing :( I continue the investigation.

```````
Last login: Sat Aug 29 18:16:08 on ttys001
iMac-de-Stanislas:~ stanislasmarcais$ /Users/stanislasmarcais/processing-java

Command line edition for Processing 0243 (Java Mode)

--help               Show this help text. Congratulations.

--sketch=<name>      Specify the sketch folder (required)
--output=<name>      Specify the output folder (optional and
                     cannot be the same as the sketch folder.)

--force              The sketch will not build if the output
                     folder already exists, because the contents
                     will be replaced. This option erases the
                     folder first. Use with extreme caution!

--build              Preprocess and compile a sketch into .class files.
--run                Preprocess, compile, and run a sketch.
--present            Preprocess, compile, and run a sketch in presentation mode.

--export             Export an application.
--no-java            Do not embed Java. Use at your own risk!
--platform           Specify the platform (export to application only).
                     Should be one of 'windows', 'macosx', or 'linux'.

The --build, --run, --present, or --export will be the final parameter
passed to Processing. Arguments passed following one of those four will
be passed through to the sketch itself, and therefore available to the
sketch via the 'args' field. To pass options understood by PApplet.main(),
write a custom main() method so that the preprocessor does not add one.
https://github.com/processing/processing/wiki/Command-Line
`````````

`````````
iMac-de-Stanislas:~ stanislasmarcais$ processing-java
/usr/bin/processing-java: line 2: /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_72.jdk/Contents/Home/jre/bin/java: No such file or directory
iMac-de-Stanislas:~ stanislasmarcais$ 
````````

**Comment by StanLepunK** [comment]
The problem is dead :)
When Processing install java-processing, it do that at the may-be wrong place.
I copy the last install of Processing-Jave in ``````usr/local/bin`````and in the `````usr/bin````now sublime work fine.
