### ISSUE TITLE
Don't --force new folder

### ISSUE THREAD

**Issue by fredguth** [b-g/processing-sublime#82]
I don't know if this is a bug or just me not knowing how to do stuff (sorry in advance if that is the case).

First build is ok.  I change the code and try to build again and the following message appears:

`The output folder already exists. Use --force to remove it.`

But it seems that --force was used:
`shell_cmd: pkill -f build; processing-java --sketch="/Users/fredguth/Desktop/basics/step 5/build" --output="/Users/fredguth/Desktop/basics/step 5/build/build-tmp" --run --force]`

Can't understand.

**Comment by b-g** [comment]
Hmm ... which processing/processing-java version and os?

**Comment by fredguth** [comment]
Command line edition for Processing 0243 (Java Mode)
Mac OSX

**Comment by ybakos** [comment]
@fredguth I can't reproduce this issue. Are you seeing this happen with all your sketches or just this one? Can you provide some more step-by-step details?

**Comment by fredguth** [comment]
I have created a video to show the error.

Same error happens  in Sublime Text 3 and Sublime Text 2 (I have ST2 in a laptop). Also, noticed some people doing Joshua Davis Skillshare course on Processing had the same error.

It happens all the time, with any sketch. Calling processing from the command line works fine.

See the video here:
https://dl.dropboxusercontent.com/u/6356493/sublime_processing.mov

**Comment by ybakos** [comment]
Thanks @fredguth I will try to replicate the error again.

**Comment by ybakos** [comment]
@fredguth When you can, please run just `processing-java` from the shell and let us know what the version number is, e.g. _Command line edition for Processing 0227 (Java Mode)_.

**Comment by ybakos** [comment]
@fredguth I still can't replicate the error. I'd like to get to the bottom of this especially if others are experience the same problem as you are.

One more thing: when you run `processing-java` from the command line I noticed you didn't specify the output folder. Could you try that and see if you see the same issue?

**Comment by fredguth** [comment]
Hmm. I think I got the problem now.  Check this:
```➜  build git:(master) ✗ processing-java --sketch=/Users/fredguth/code/processing/Skillshare/HYPE_basics/step4/build --output=/Users/fredguth/code/processing/Skillshare/HYPE_basics/step4/build/build-tmp --run --force
The output folder already exists. Use --force to remove it.
➜  build git:(master) ✗ processing-java --force --sketch=/Users/fredguth/code/processing/Skillshare/HYPE_basics/step4/build --output=/Users/fredguth/code/processing/Skillshare/HYPE_basics/step4/build/build-tmp --run
Listening for transport dt_socket at address: 8776```

**Comment by ybakos** [comment]
Thanks @fredguth a fix is [in progress](https://github.com/b-g/processing-sublime/commit/9b7d2e71674e2f0886bb27e7dfb21b58bbb4f23f).

**Comment by fredguth** [comment]
changed my build to:
"cmd": ["/usr/local/bin/processing-java", "--force", "--sketch=$file_path", "--output=$file_path/build-tmp", "--run"],

and now it is working :-)

**Comment by fredguth** [comment]
Notice that I have to add the Path manually.  For some reason, without specifying /usr/local/bin it doesn't work. The path printed in Sublime doesn't include it, despite this directory being part of my $PATH.
