### ISSUE TITLE
Win Error 2. 

### ISSUE THREAD

**Issue by hezeng1** [b-g/processing-sublime#83]
Dear b-g, 
    My sublime text 3 was working when I first initially installed it , along with processing. However after three days or so, whenever I try to build my program the console presents me with this error. 
[WinError 2] The system cannot find the file specified
[cmd: ['processing-java', '--sketch=C:\\Users\\Herman\\Documents\\apjava\\Lightning', '--output=C:\\Users\\Herman\\Documents\\apjava\\Lightning/build-tmp', '--run', '--force']]
[dir: C:\Users\Herman\Documents\apjava\Lightning]
[path: C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Skype\Phone\]
[Finished]
. I've been looking all over forums for solutions, but I just can't find one. 
       Help would be appreciated Thank you,
                           Herman

**Comment by ybakos** [comment]
@hezeng1 I recommend asking your question on the Processing forum. GitHub Issues is for reporting bugs about the package, not for seeking support.

If it worked before, but does not work now, you have changed something on your system. The first thing I would do is try to run `processing-java` from the command line:

- Open a console window (windows-R, then type `cmd` and hit enter)
- type `processing-java` and hit enter.

If you get a "command not found" or similar, then use Processing to re-install `processing-java` and try again.

**Comment by SpiderGoose** [comment]
cool

**Comment by eryup** [comment]
^
