### ISSUE TITLE
color datatype not highlighted

### ISSUE THREAD

**Issue by ybakos** [b-g/processing-sublime#84]
We lost Processing's color datatype highlighting with the latest revision to the syntax rules.

Should this be highlighted like the primitives (double, int, etc) or like abstract data types (PShape)?

I suggest using the primitive style highlighting, since color is really just a number.

Commit coming.

**Comment by ybakos** [comment]
@b-g Let me know what you think.

**Comment by b-g** [comment]
@ybakos Sorry for the silence, very crazy here!
:+1: color = int = primitive style highlighting
