### ISSUE TITLE
Since updating to Processing 3, error in buidling within sublime 3

### ISSUE THREAD

**Issue by mheesakkers** [b-g/processing-sublime#87]
Error message:
/usr/bin/processing-java: line 2: /Applications/Processing.app/Contents/PlugIns/jdk1.7.0_55.jdk/Contents/Home/jre/bin/java: No such file or directory

Know how to fix this?

**Comment by ybakos** [comment]
Open a terminal and type `processing-java` and tell us what the output is.

(Also, please note that GitHub issues are for bugs, not for technical support - I encourage you to post a message in the Processing forum.)

**Comment by mheesakkers** [comment]
I'm sorry! Just needed to re install java via processing 3 for building with the console. My fault!
