### ISSUE TITLE
cannot build with no such file or directory

### ISSUE THREAD

**Issue by lianyile** [b-g/processing-sublime#94]
in the console, it appears "/usr/local/bin/processing-java: line 2: cd: /Applications/Processing 3.app/Contents/Java: No such file or directory
[Finished in 0.0s with exit code 1]"

but my processing in the applications folder is called "Processing" without 3. 

I have tried the fix mac path, and it does not work.

I am running Processing 3 on El Capitan.

Thanks

**Comment by ybakos** [comment]
Please use the Processing menu to re-install the command line tool, and try the build in Sublime again.

**Comment by lianyile** [comment]
thanks, ybakos, problems solved, but another problem is that after I run several times, the java icon just pops at the dock , no display window appears any more...I do not know why...

Thank you !
