### ISSUE TITLE
Compiling speed

### ISSUE THREAD

**Issue by sldx** [b-g/processing-sublime#96]
I notice a big difference in speed for running a sketch in native Processing (3) and Sublime. It's probabily more than double.

For example, a certain sketch takes about 2 seconds to launch from Processing and 5 from Sublime, so about 2.5x.

Any idea why and if it's possible to speed up?

**Comment by ybakos** [comment]
I know what you mean. Sublime's build is a little slower than the Processing IDE, although my speeds in both Processing and Sublime are both faster than the numbers you mention. This is system-dependent. There's nothing we can do about this.

For example, you'll probably find that running your sketch with `processing-sublime` is just as "slow" as building with Sublime.
