### ISSUE TITLE
Syntax: constructor with uppercase letters only

### ISSUE THREAD

**Issue by adminradio** [b-g/processing-sublime#99]
If there is a constructor with only uppercase letters -- like OPC() -- most of the following highlights are taken wrong.
It looks like, that the constructor would be highlighted as a constant.

See picture:
![p5_syntax_wrong](https://cloud.githubusercontent.com/assets/2880143/11123341/9aba5152-895f-11e5-8f90-8de2868e979e.png)

**Comment by b-g** [comment]
thanks! But no idea ... please provide example.

**Comment by adminradio** [comment]
sorry, hit return by mistake. Issue updated.

**Comment by b-g** [comment]
Hi @kylefleming (= the master of syntax highlighting). Any ideas/hints or fixes for us? Sorry to bother! All the Best, Benedikt
